name: Auto-assign to project(s)

on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]

jobs:
  add-to-project:
    runs-on: ubuntu-latest
    name: Add PR/issue to project(s)
    steps:
    - name: Assign NEW issues and NEW pull requests to project ETV Member Platform
      uses: actions/add-to-project@v0.4.0
      if: github.event.action == 'opened'
      with:
        project-url: https://github.com/orgs/hoco-etv/projects/4
        github-token: ${{ secrets.PROJECT_MGMT_PAT }}
